next_steps:
  - path: 01-login
    list:
    - text: Configure other identity providers
      icon: 345
      href: "/identityproviders"
    - text: Enable multifactor authentication
      icon: 345
      href: "/multifactor-authentication"
    - text: Learn about anomaly detection
      icon: 345
      href: "/anomaly-detection"
    - text: Learn about the user profile structure
      icon: 345
      href: "/user-profile/normalized/oidc"
    - text: Learn about scopes
      icon: 345
      href: "/scopes"
sample_download_required_data:
  - client
