next_steps:
  - path: 01-login
    list:
    - text: Configure other identity providers
      icon: 345
      href: "/identityproviders"
    - text: Enable multifactor authentication
      icon: 345
      href: "/multifactor-authentication"
    - text: Learn about anomaly detection
      icon: 345
      href: "/anomaly-detection"
    - text: Learn about options for storing tokens
      icon: 345
      href: "/security/store-tokens"
    - text: Learn about the user profile structure
      icon: 345
      href: "/user-profile/normalized/oidc"
    - text: In-depth details about user profile
      icon: 345
      href: "/user-profile/user-profile-details"
sample_download_required_data:
  - client
