## ------------------------------------------------------------
## Quickstart Configuration
## This document contains configuration for the quickstart
##
## ------------------------------------------------------------

categories:
  -
    id: "start"
    name: "Getting Started"
    links:
      -
        name: "Introduction to Auth0"
        href: "https://auth0.com/video-tutorials/main/intro"
      -
        name: "Creating your first Application"
        href: "https://auth0.com/video-tutorials/creating-your-first-app/register-an-application"
      -
        name: "Getting Started with Lock"
        href: "https://auth0.com/video-tutorials/getting-started-with-lock/implementing-lock"
      -
        name: "Using Rules"
        href: "https://auth0.com/video-tutorials/advanced-usage-of-auth0/using-rules"
  -
    id: "product"
    name: "Product"
    description: "Learn how to use the key features of Auth0"
    links:
      -
        name: "Overview"
        icon: "icon-budicon-121"
        description: "What is Auth0 and how can it help you build applications."
        href: "/overview"
      -
        name: "Applications"
        icon: "icon-budicon-349"
        description: "Understanding an application in the context of Auth0."
        href: "/applications"
      -
        name: "Rules"
        icon: "icon-budicon-173"
        description: "Extend and enhance Auth0 with your custom logic."
        href: "/rules"
      -
        name: "Identity Providers"
        icon: "icon-budicon-297"
        description: "Discover all the of identity providers Auth0 supports."
        href: "/identityproviders"
      -
        name: "Single Sign-On"
        icon: "icon-budicon-170"
        description: "Provide a better user experience with single sign-on."
        href: "/sso/single-sign-on"
      -
        name: "User Profile"
        icon: "icon-budicon-289"
        description: "Learn how to use and add metadata to the user profile."
        href: "/user-profile"
      -
        name: "Multifactor Authentication"
        icon: "icon-budicon-243"
        description: "Add additional security with a second factor of authentication."
        href: "/mfa"
      -
        name: "Passwordless Authentication"
        icon: "icon-budicon-499"
        description: "Authenticate users without a password using SMS, Email, or TouchID."
        href: "/connections/passwordless"
      -
        name: "Auth0 Appliance"
        icon: "icon-budicon-359"
        description: "Deploy Auth0 to your own cloud or datacenter."
        href: "/appliance"
  -
    id: "api"
    name: "API"
    description: "The core Auth0 APIs for Authentication and Management"
    sections:
      auth-endpoints:
        name: "Authentication API"
        description: "Perform enterprise authentication or OpenID operations using these APIs."
        href: "/auth-api/"
      explorer:
        name: "Management API"
        description: "Perform administrative tasks such as creating accounts or changing settings with the Management API."
        href: "/api/v2/"
      announcements:
        name: "Releases & Updates"
        links:
          -
            name: "Platform Releases"
            href: "https://releases.auth0.com"
          -
            name: "Content & SDK Updates"
            href: "/updates"
  -
    id: "platform"
    name: "Platforms"
    description: ""
    links:
      -
        name: "Web Developers"
        href: "/platforms/web"
      -
        name: "Single Page App Developers"
        href: "/platforms/spa"
      -
        name: "API Developers"
        href: "/platforms/api"
      -
        name: "Mobile Developers"
        href: "/platforms/mobile"
  -
    id: "ui-component"
    name: "UI Components"
    links:
      -
        name: "Lock for Web"
        description: "Auth UI for your web app"
        href: "/libraries/lock"
      -
        name: "Lock for iOS"
        description: "Native iOS Authentication UI"
        href: "/libraries/lock-ios"
      -
        name: "Lock for Android"
        description: "Native Android Authentication UI"
        href: "/libraries/lock-android"
  -
    id: "dev-center"
    name: "Developer Centers"
    description: "Explore content by language and platform"
    links:
      -
        name: "Android"
        slug: "android"
        href: "/dev-centers/android"
      -
        name: "iOS"
        slug: "ios"
        href: "/dev-centers/ios"
      -
        name: "Java"
        slug: "java"
        href: "/dev-centers/java"
      -
        name: "Javascript"
        slug: "Javascript"
        href: "/dev-centers/javascript"
      -
        name: ".NET"
        slug: "net"
        href: "/dev-centers/dotnet"
      -
        name: "Node"
        slug: "node"
        href: "/dev-centers/node"
      -
        name: "Python"
        slug: "python"
        href: "/dev-centers/python"
      -
        name: "Ruby"
        slug: "ruby"
        href: "/dev-centers/ruby"
      -
        name: "More"
        slug: "other"
        href: "/dev-centers/all"
  -
    id: "web-framework"
    name: "Web Frameworks"
    description: ""
    links:
      -
        name: "AngularJS"
        href: "/web-frameworks/angular"
      -
        name: "EmberJS"
        href: "/web-frameworks/ember"
      -
        name: "React"
        href: "/web-frameworks/react"
      -
        name: "More"
        slug: "other"
        href: "/web-frameworks/all"
  -
    id: "how-to"
    name: "Guides"
    description: "Learn how to get the most out of Auth0"
    links:
      -
        name: "Refresh Tokens"
        icon: "icon-budicon-754"
        href: "/refresh-token"
        description: "How to securely renew id tokens within your apps."
      -
        name: "Importing and Migrating Users to Auth0"
        icon: "icon-budicon-754"
        href: "/connections/database/migrating"
        description: "Import users from existing applications into Auth0."
      -
        name: "Customizing Sign Up Forms"
        icon: "icon-budicon-754"
        href: "/custom-signup"
        description: "Deliver a customized signup experience to your users."
      -
        name: "Linking Accounts"
        icon: "icon-budicon-754"
        href: "/link-accounts"
        description: "Unify a single user's identity using different identity providers."
      -
        name: "Logout"
        icon: "icon-budicon-754"
        href: "/logout"
        description: "Learn about clearing sso cookies and other logout operations."
      -
        name: "Connecting Active Directory"
        icon: "icon-budicon-754"
        href: "/connections/enterprise/active-directory"
        description: "Learn how to use Auth0 with Active Directory."
      -
        name: "Using and Configuring SAML"
        icon: "icon-budicon-754"
        href: "/saml-configuration"
        description: "Get your SAML application set up for authentication and single sign-on."
      -
        name: "Custom Password Strength"
        icon: "icon-budicon-754"
        href: "/password-strength"
        description: "Set the password strength to enhance your app's security."
      -
        name: "Configure Emails"
        icon: "icon-budicon-778"
        href: "/email"
        description: "Learn how to configure the account management emails that Auth0 sends."
