## ------------------------------------------------------------
## Quickstart Configuration
## This document contains configuration for the quickstart
##
## ------------------------------------------------------------

apptypes:
  - title: Native mobile app
    name: native-mobile
    description: An app that runs natively in devices
    example: "eg: iOS SDK"
    budicon: 243

  - title: Single page app
    name: spa
    description: A JavaScript front-end app that uses an API
    example: "eg: AngularJS + NodeJS"
    budicon: 349

  - title: Regular web app
    name: webapp
    description: Traditional web app (with refresh)
    example: "eg: Java ASP.NET"
    budicon: 378

  - title: Hybrid mobile app
    name: hybrid
    description: A JS/HTML5 mobile app that runs in devices
    example: "eg: PhoneGap Ionic"
    budicon: 243

  - title: Backend/API
    name: backend
    description: An API or service that does JWT validation
    example: "eg: Custom API"
    budicon: 649
