## ------------------------------------------------------------
## Top Nav Configuration
## This document contains configuration for the top nav sections
##
## ------------------------------------------------------------

- id: "articles"
  title: "Articles"
  url: "/getting-started"

# - id: "sdks"
#   title: "SDKs"
#   url: "/sdks"

- id: "apis"
  title: "Auth0 APIs"
  url: "/api/info"

- id: "quickstarts"
  title: "QuickStarts"
  url: "/quickstarts"

- id: "libraries"
  title: "Libraries"
  url: "/libraries"

- id: "appliance"
  title: "PSaaS Appliance"
  url: "/appliance"
