## ------------------------------------------------------------
## Top Nav Configuration
## This document contains configuration for the top nav sections
##
## ------------------------------------------------------------

- id: "articles"
  title: "Articles"
  url: "/overview"

# - id: "sdks"
#   title: "SDKs"
#   url: "/sdks"

- id: "apis"
  title: "APIs"
  url: "/api/info"

- id: "quickstarts"
  title: "QuickStarts"
  url: "/quickstarts"

- id: "appliance"
  title: "Appliance"
  url: "/appliance"
