## ------------------------------------------------------------
## Top Nav Configuration
## This document contains configuration for the top nav sections
##
## ------------------------------------------------------------

- id: "articles"
  title: "Articles"
  url: "/getting-started"
  folder: ""
  default: true

# - id: "sdks"
#   title: "SDKs"
#   url: "/sdks"

- id: "apis"
  title: "Auth0 APIs"
  url: "/api/info"
  folder: "api"

- id: "quickstarts"
  title: "QuickStarts"
  url: "/quickstarts"
  folder: "quickstart"

- id: "libraries"
  title: "Libraries"
  url: "/libraries"
  folder: "libraries"

- id: "appliance"
  title: "PSaaS Appliance"
  url: "/appliance"
  folder: "appliance"
