## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

  - title: Getting Started
    url: "/overview"
    children:
      - title: Overview
        url: /overview

      - title: Developer Videos
        url: /videos
        children:

        - title: Developer Overview
          url: /videos/developer-overview

        - title: Rules
          url: /videos/rules

        - title: Session & Cookies
          url: /videos/session-and-cookies

      - title: Architecture Scenarios
        url: /architecture-scenarios

        children:
          - title: Server Client + API
            url: /architecture-scenarios/application/server-api

          - title: SSO for Regular Web Apps
            url: /architecture-scenarios/application/web-app-sso

          - title: SPA + API
            url: /architecture-scenarios/application/spa-api

          - title: Mobile + API
            url: /architecture-scenarios/application/mobile-api

          - title: SAML for Regular Web Apps
            url: /architecture-scenarios/application/web-saml

          - title: B2B + B2E
            url: /architecture-scenarios/business/b2b-b2e

          - title: B2B
            url: /architecture-scenarios/business/b2b

          - title: B2C
            url: /architecture-scenarios/business/b2c
          
          - title: B2E
            url: /architecture-scenarios/business/b2e
      - title: Pre-launch Tips
        url: /prelaunch-tips  

  - title: "Clients"
    url: "/clients"
    children:

      - title: Overview
        url: /clients

      - title: Connections
        url: /clients/connections

  - title: "APIs"
    url: "/apis"
    children:

      - title: "Overview"
        url: "/apis"

      - title: "Authorization API Index"
        url: "/api-auth"

      - title: "OIDC Conformant Authentication"
        url: "/api-auth/intro"

      - title: "OIDC Adoption Guide"
        url: "/api-auth/tutorials/adoption"

      - title: "Which OAuth Flow to Use"
        url: "/api-auth/which-oauth-flow-to-use"

      - title: "APIs & Server-side Apps"
        url: "/api-auth/grant/authorization-code"

      - title: "APIs & Mobile Apps"
        url: "/api-auth/grant/authorization-code-pkce"

      - title: "APIs & Client-side Apps"
        url: "/api-auth/grant/implicit"

      - title: "APIs & CLIs"
        url: "/api-auth/grant/client-credentials"

      - title: "APIs & Trusted Clients"
        url: "/api-auth/grant/password"

      - title: "Dynamic Client Registration"
        url: "/api-auth/dynamic-client-registration"

      - title: "Verify Access Tokens"
        url: "/api-auth/tutorials/verify-access-token"

  - title: "Connections"
    url: "/connections"
    children:
      - title: "Overview"
        url: "/connections"

      - title: "Username/Password"
        url: "/connections/database"

      - title: "Social/Enterprise"
        url: "/identityproviders"
        children:
          - title: "Custom Social Extensions"
            url: "/extensions/custom-social-extensions"

      - title: "Custom Database"
        url: "/connections/database/mysql"

      - title: "Passwordless Authentication"
        url: "/connections/passwordless"
        children:

          - title: "Using Email"
            url: "/connections/passwordless/email"

          - title: "Using SMS"
            url: "/connections/passwordless/sms"

          - title: "FAQ"
            url: "/connections/passwordless/faq"

  - title: "Rules"
    url: "/rules"
    children:

      - title: "Overview"
        url: "/rules"

      - title: "User Metadata in Rules"
        url: "/rules/metadata-in-rules"

      - title: "Deploy Rules with GitHub"
        url: "/extensions/github-deploy"

      - title: "Deploy Rules with Bitbucket"
        url: "/extensions/bitbucket-deploy"

      - title: "Deploy Rules with GitLab"
        url: "/extensions/gitlab-deploy"

  - title: "Hooks (Beta)"
    url: "/hooks"
    children:

      - title: "Index"
        url: "/hooks"

      - title: "Overview"
        url: "/hooks/overview"

      - title: "Extensibility Points"
        url: "/hooks/extensibility-points"

      - title: "Using the Auth0 CLI"
        url: "/hooks/cli"

      - title: "Using the Dashboard"
        url: "/hooks/dashboard"

  - title: "Email"
    url: "/email"
    children:
      - title: "Overview"
        url: "/email"

      - title: "Custom Email Handling"
        url: "/email/custom"

      - title: "Customizing Your Emails"
        url: "/email/templates"

      - title: "Use your own SMTP Email Provider"
        url: "/email/providers"

      - title: "Liquid Syntax in Email Templates"
        url: "/email/liquid-syntax"

      - title: "Set up a Test SMTP Provider"
        url: "/email/testing"

  - title: "Password Policies"
    url: "/connections/database/password-options"
    children:
      - title: "Password Options"
        url: "/connections/database/password-options"

      - title: "Password Strength"
        url: "/connections/database/password-strength"

  - title: "User Management"
    url: "/user-profile"
    children:
      - title: "User Profiles"
        url: "/user-profile"

      - title: "User Metadata"
        url: "/metadata"

      - title: "User Impersonation"
        url: "/user-profile/user-impersonation"

      - title: "Delegated Administration"
        url: "/extensions/delegated-admin"

      - title: "Authorization"
        url: "/extensions/authorization-extension/v2"

  - title: "Multifactor Authentication"
    url: "/multifactor-authentication"
    children:
      - title: "Overview"
        url: "/multifactor-authentication"

      - title: "Guardian"
        url: "/multifactor-authentication/guardian"
        children:
          - title: "For Administrators"
            url: "/multifactor-authentication/administrator"

          - title: "For Developers"
            url: "/multifactor-authentication/developer"

          - title: "For Users"
            url: "/multifactor-authentication/guardian/user-guide"

      - title: "Google Authenticator"
        url: "/multifactor-authentication/google-authenticator"

      - title: "Duo Security"
        url: "/multifactor-authentication/duo"

  - title: "Anomaly Detection"
    url: "/anomaly-detection"

  - title: "Addons/Third-Party Applications"
    url: "/addons"

  - title: "Support"
    url: "/support"
    children:
      - title: "Support Matrix"
        url: "/support/matrix"

      - title: "SLA"
        url: "/support/sla"

      - title: "Tickets"
        url: "/support/tickets"

      - title: "Manage Subscription"
        url: "/support/subscription"

  - title: "Professional Services"
    url: "/services"

apis:

  - title: "Overview"
    url: "/api/info"

  - title: "Testing with Postman"
    url: "/api/postman"

  - title: Authentication API
    url: "/api/authentication"
    external: true
    forceFullReload: true

  - title: Management API
    url: "/api/management/v2/tokens"
    forceFullReload: true
    expanded: true
    children:

      - title: API Tokens
        url: "/api/management/v2/tokens"
        forceFullReload: true

      - title: Query String Syntax
        url: "/api/management/v2/query-string-syntax"
        forceFullReload: true

      - title: User Search
        url: "/api/management/v2/user-search"
        forceFullReload: true

      - title: API Explorer
        url: "/api/management/v2/"
        forceFullReload: true
        external: true

libraries:

  - title: "Overview"
    url: "/libraries"

  - title: "Lock for Web"
    url: "/libraries/lock/v10"
    children:

      - title: "Overview"
        url: "/libraries/lock/v10"

      - title: "Configuration Options"
        url: "/libraries/lock/v10/customization"

      - title: "API Reference"
        url: "/libraries/lock/v10/api"

      - title: "UI Customization"
        url: "/libraries/lock/v10/ui-customization"

      - title: "v10 Migration Guide"
        url: "/libraries/lock/v10/migration-guide"

      - title: "Internationalization"
        url: "/libraries/lock/v10/i18n"

      - title: "Customizing Errors"
        url: "/libraries/lock/v10/customizing-error-messages"

      - title: "Lock with auth0.js"
        url: "/libraries/lock/v10/auth0js"

      - title: "Popup Mode"
        url: "/libraries/lock/v10/popup-mode"

  - title: "Lock for iOS"
    url: "/libraries/lock-ios/v2"
    children:

      - title: "Overview"
        url: "/libraries/lock-ios/v2"

      - title: "Styles Customization"
        url: "/libraries/lock-ios/v2/customization"

      - title: "Behavior Configuration"
        url: "/libraries/lock-ios/v2/configuration"

      - title: "Custom Fields"
        url: "/libraries/lock-ios/v2/custom-fields"

      - title: "Internationalization"
        url: "/libraries/lock-ios/v2/internationalization"

      - title: "Version 2 Migration Guide"
        url: "/libraries/lock-ios/v2/migration"

      - title: "Version 1 Documentation"
        url: "/libraries/lock-ios/v1"

  - title: "Lock for Android"
    url: "/libraries/lock-android"
    children:

      - title: "Overview"
        url: "/libraries/lock-android"

      - title: "Configuration Options"
        url: "/libraries/lock-android/configuration"

      - title: "Custom Auth Providers"
        url: "/libraries/lock-android/custom-authentication-providers"

      - title: "Custom Signup Fields"
        url: "/libraries/lock-android/custom-fields"

      - title: "Custom Theming"
        url: "/libraries/lock-android/custom-theming"

      - title: "Migration v1 to v2"
        url: "/libraries/lock-android/migration-guide"

      - title: "Passwordless Auth"
        url: "/libraries/lock-android/passwordless"

      - title: "Internationalization"
        url: "/libraries/lock-android/internationalization"

  - title: "Lock vs. Custom UI"
    url: "/libraries/when-to-use-lock"

  - title: "Auth0 SDK for Web"
    url: "/libraries/auth0js"
    children:

      - title: "Auth0.js v8"
        url: "/libraries/auth0js/v8"

      - title: "Migration Guide v8"
        url: "/libraries/auth0js/v8/migration-guide"

      - title: "Auth0.js v7"
        url: "/libraries/auth0js/v7"

  - title: "Auth0 SDK for iOS"
    url: "/libraries/auth0-swift"

  - title: "Auth0 SDK for Android"
    url: "/libraries/auth0-android"

appliance:

  - title: "Introduction"
    url: "/appliance"

  - title: "Support"
    url: "/appliance/critical-issue"
    expanded: true
    children:
      - title: Enterprise Support
        url: /onboarding/enterprise-support
      - title: Critical Issue
        url: /appliance/critical-issue

  - title: Appliance Planning
    url: /appliance/appliance-overview
    expanded: true
    children:
      - title: Overview
        url: /appliance/appliance-overview
      - title: Geographic High-Availability
        url: /appliance/geo-ha
      - title: Infrastructure Requirements
        url: /appliance/infrastructure
      - title: Roles and Responsibilities
        url: /appliance/raci
      - title: Customer Onboarding
        url: /onboarding/appliance-sprint
      - title: Private Cloud Requirements
        url: /appliance/private-cloud-requirements

  - title: "Appliance Administration"
    url: "/appliance/admin"
    expanded: true
    children:
      - title: Administrator's Manual
        url: /appliance/admin
      - title: Dashboard/Configuration Area
        url: /appliance/dashboard
      - title: Monitoring Tools
        url: /appliance/monitoring
      - title: Command-Line Interface Tools
        url: /appliance/cli
      - title: Automatic Tenant Creation
        url: /appliance/admin/creating-tenants
      - title: Node Module Availibility
        url: /appliance/modules
      - title: Webtasks
        url: /appliance/webtasks
      - title: Extensions
        url: /appliance/extensions
      - title: Disaster Recovery
        url: /appliance/geo-ha/disaster-recovery
      - title: Release Notes
        url: https://auth0.com/changelog/appliance
        external: true
        forceFullReload: true
