lock_url: 'https://cdn.auth0.com/js/lock/11.14/lock.min.js'
lock_urlv10: 'https://cdn.auth0.com/js/lock/10.24.3/lock.min.js'
lock_urlv11: 'https://cdn.auth0.com/js/lock/11.14/lock.min.js'
auth0js_url: 'https://cdn.auth0.com/js/auth0/9.11/auth0.min.js'
auth0js_urlv9: 'https://cdn.auth0.com/js/auth0/9.10/auth0.min.js'
auth0js_urlv8: 'https://cdn.auth0.com/js/auth0/8.12.3/auth0.min.js'
auth0js_urlv7: 'https://cdn.auth0.com/w2/auth0-7.6.1.min.js'
auth0spajs_url: 'https://cdn.auth0.com/js/auth0-spa-js/1.2/auth0-spa-js.production.js'
auth0_community: 'https://community.auth0.com/'
