next_steps:
  - path: 01-login
    list:
    - text: Configure other identity providers
      icon: 350
      href: "/identityproviders"
    - text: Enable multifactor authentication
      icon: 345
      href: "/multifactor-authentication"
    - text: Learn about anomaly detection
      icon: 345
      href: "/anomaly-detection"
    - text: Learn about options for storing tokens
      icon: 345
      href: "/security/store-tokens"
  - path: 02-user-profile
    list:
    - text: Learn about the user profile structure
      icon: 350
      href: "/user-profile/normalized/oidc"
    - text: Learn about scopes
      icon: 345
      href: "/scopes"
    - text: In-depth details about user profile
      icon: 345
      href: "/user-profile/user-profile-details"
  - path: 03-calling-an-api
    list:
    - text: Learn about custom APIs
      icon: 350
      href: "/api"
    - text: Introduction to API authorization
      icon: 345
      href: "/api-auth"
  - path: 04-authorization
    list:
    - text: Learn about scopes
      icon: 345
      href: "/scopes"
  - path: 05-token-renewal
    list:
    - text: Learn about token renewal
      icon: 345
      href: "/api-auth/tutorials/silent-authentication"
sample_download_required_data:
  - client
